---
title: "data generation"
author: "Zern Ke"
date: "2024-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Create folders for factorial Experiments

```{r}
# # Define levels and factor names
# levels <- c("-", "+")
# factors <- c("A", "B", "C", "D")
# 
# # Generate full 2^4 factorial design
# design <- expand.grid(rep(list(levels), 4))
# colnames(design) <- factors
# 
# # Generate compact folder names like "----", "+-+-", etc.
# folder_names <- apply(design, 1, paste0, collapse = "")
# 
# 
# # Create each folder
# for (name in folder_names) {
#   dir.create(file.path(name), showWarnings = FALSE)
# }


```


# libarary

```{r warning=FALSE, message=FALSE}
library(tidyverse) # for data manipulation
library(fastDummies)
library(MASS)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(patchwork)
```


```{r ordinal variable generation}
generate_y <- function(X, omega, K, q) {
  # Ensure quantile is sorted
  q <- sort(q)
  
  # Number of samples (rows in X)
  n <- nrow(X)
  
  # Generate normally distributed noise for each sample
  epsilon <- rnorm(n, mean = 0, sd = 1)
  
  # Compute the latent variable y* for all samples
  y_star <- X %*% omega + epsilon  # Matrix-vector multiplication
  
  # calculate theta
  theta <- quantile(y_star, probs=q)
  
  # Determine the categorical outcome y
  y <- apply(y_star, 1, function(y_i) sum(y_i > theta) + 1)
  
  return(y)
}
```

```{r big daatset distribution set range}
gen_range = function(x, a, b, n){
  x = x[x>=a & x<=b]
  m = length(x)
  if(m>=n){
    x = x[sample(m,n,rep=F)]
  }
  else{
    x = x[sample(m,n,rep=T)]
  }

  return(x)

}

```




# For 5 binary, 2 categorical (4, 6), 2 ordinal, 1 continuous -> 10 to 16

```{r generate distribution f1}
generate_data <- function(n=500, z_rho=0.8, mu=c(1, 2, 3)){ 
  
    sig = matrix(z_rho, 3, 3)
    diag(sig) = 1
    z_all = mvrnorm(n, mu=mu, Sigma=sig)
    
    # Binary variables
    # add categorical variables with 1 latent dim
    z = z_all[, 1]
    W1 <- rbinom(n, size=1, prob=plogis(-1+0.1*z)) 
    W2 <- rbinom(n, size=1, prob=plogis(0.3*z))
    W3 <- rbinom(n, size = 1, prob = plogis(-3+z))
    W4 <- rbinom(n, size = 1, prob = plogis(-1 + 0.1*z))
    W5 <- rbinom(n, size = 1, prob = plogis(2 + 0.5*z))
    
    W6 <- rbinom(n, size = 3, prob = plogis(-0.1 + 0.3*z))
    W7 <- rbinom(n, size = 5, prob = plogis(-0.8 + 0.2*log(5+z)))
    
    # add support differenc
    W6 <- ifelse(W6 == 3, 1, W2)
    W7 <- ifelse(W7 == 4, 2, W3)
    W7 <- ifelse(W7 == 5, 3, W3)

    # Ordinal variables
    z = z_all[, c(1, 2)]
    W8 = generate_y(z, omega = c(0.8, 0.5), K = 4, q=c(0.25, 0.5, 0.75))
    W9 = generate_y(z, omega = c(0.5, 0.8), K = 4, q=c(0.1, 0.2, 0.3))
    
    # Continuous variables
    zc = z_all[, c(1, 3)] 
    W10 = zc[, 1] * zc[, 2] + rnorm(n, mean = 0, sd = 1)
    
    return(tibble(W1, W2, W3, W4, W5, W6, W7, W8, W9, W10))
}
```



```{r generate distribution f2}

generate_data2 <- function(n=50000, z_rho=0.8, mu=c(2, 3, 4), trt){ 
    sig = matrix(z_rho, 3, 3)
    diag(sig) = 1
    z_all = mvrnorm(n, mu=mu, Sigma=sig) 
    
    # Binary variables
    z = z_all
    W1 <- rbinom(n, size=1, prob=plogis(-1+0.3*z[, 1])) 
    W2 <- rbinom(n, size=1, prob=plogis(0.1*z[,1]))
    W3 <- rbinom(n, size = 1, prob = plogis(-0.3+6*z[,1]))
    W4 <- rbinom(n, size = 1, prob = plogis(-1 + 0.4*z[,2]))
    W5 <- rbinom(n, size = 1, prob = plogis(0.8 + 0.5*z[,2]))
    
    # Categorical variables
    W6 <- rbinom(n, size = 3, prob = plogis(-0.5 + 0.6*z))
    W7 <- rbinom(n, size = 5, prob = plogis(-0.4 + 0.2*exp(0.5*z)))

    # add support difference
    # W9 <- ifelse(W9 == 3, 1, W9)
    # W10 <- ifelse(W10 == 4, 2, W10)
    # W10 <- ifelse(W10 == 5, 3, W10)

    # add 5 ordinal variables with 2 latent dim
    z = z_all[, 1:2]

    W8 = generate_y(z, omega = c(0.1, 0.5), K = 4, q=c(0.2, 0.4, 0.6))
    W9 = generate_y(z, omega = c(0.2, 0.9), K = 4, q=c(0.2, 0.4, 0.6))
  
    
    # add 6 continuous variables with 2 latent dim
    zc = z_all[, c(1, 3)]
    
    W10 = zc[, 1] * 5 * zc[, 2] + rnorm(n, mean = 0, sd = 1)
    W10 = gen_range(W10, -5, 33, n)
    
    return(tibble(W1, W2, W3, W4, W5, W6, W7, W8, W9, W10))
}
```



```{r generate distribution f3}

generate_data3 <- function(n=50000, z_rho=0.8, mu = c(3, 5, 7)){ 
    sig = matrix(z_rho, 3, 3)
    diag(sig) = 1
    z_all = mvrnorm(n, mu=mu, Sigma=sig) 
    
    # Binary variables
    z = z_all
    W1 <- rbinom(n, size=1, prob=plogis(-1+0.3*z[, 1])) 
    W2 <- rbinom(n, size=1, prob=plogis(0.1*z[,1]))
    W3 <- rbinom(n, size = 1, prob = plogis(-0.3+6*z[,1]))
    W4 <- rbinom(n, size = 1, prob = plogis(-1 + 0.4*z[,2]))
    W5 <- rbinom(n, size = 1, prob = plogis(0.8 + 0.5*z[,2]))
    
    
    W6 <- rbinom(n, size = 3, prob = plogis(-1.5 + 1.6*z))
    W7 <- rbinom(n, size = 5, prob = plogis(-2.4 + 1.2*exp(0.5*z)))


    z = z_all[, 1:2]
    W8 = generate_y(z, omega = c(0.1, 0.5), K = 4, q=c(0.5, 0.8, 0.9))
    W9 = generate_y(z, omega = c(0.2, 0.9), K = 4, q=c(0.8, 0.85, 0.9))

    zc = z_all[, c(1, 3)]
    
    W10 = zc[, 1] * 5* zc[, 2] + rnorm(n, mean = 0, sd = 1)

    return(tibble(W1, W2, W3, W4, W5, W6, W7, W8, W9, W10))
}

```




## Simulation repeat 20 times

```{r}
set.seed(12345)
seeds = sample.int(1e8, 20)

for (i in seq_len(20)){
  set.seed(seeds[i])
  
  n_trt=2000
  n_big1 = 40000
  n_big2 = 60000
  n_big3 = 50000
  
  # 0.8-0.85 for high correlation
  # 0-0.1 for low correlation
  z_rho = runif(1, 0.8, 0.85)
  mu_trt = c(1, 2, 3) + rnorm(3, 0, 0.1)
  mu_big2 = c(2, 3, 4) + rnorm(3, 0, 0.1)
  mu_big3 = c(3, 5, 7) + rnorm(3, 0, 0.1)
  
  # trts
  trt = generate_data(n=n_trt, z_rho=z_rho, mu=mu_trt)
  print(sum(is.na(trt)))


  # big
  # real world big database with proportion 
  R1 = generate_data(n=n_big1, z_rho = z_rho, mu=mu_trt)
  R2 = generate_data2(n=n_big2, z_rho = z_rho, mu=mu_big2, trt = trt)
  R3 = generate_data3(n=n_big3, z_rho = z_rho, mu = mu_big3)
  big = rbind(R1, R2, R3)
  print(sum(is.na(big)))

  # create folder to save the simulations
  # n_trt, correlation, proportion, covariates dim
  dir_name = sprintf("++--/rep%d", i)
  if (!dir.exists(dir_name)) dir.create(dir_name)
  
  saveRDS(trt, file = file.path(dir_name, "trt.rds"))
  saveRDS(big, file = file.path(dir_name, "big.rds"))
  
  saveRDS(list(seed=seeds[i]), file = file.path(dir_name, "metadata.rds"))
}
```





# For 8 binary, 4 categorical(4, 6, 5, 5) , 5 ordinal, 3 continuous --> 20 to 28

```{r 20 dim generate distribution f1}
generate_data <- function(n=500, z_rho=0.8, mu=c(1, 2, 3)){ 
  
    sig = matrix(z_rho, 3, 3)
    diag(sig) = 1
    z_all = mvrnorm(n, mu=mu, Sigma=sig)
    
    # Binary variables
    z = z_all
    W1 <- rbinom(n, size=1, prob=plogis(-1+0.1*z[, 1])) 
    W2 <- rbinom(n, size=1, prob=plogis(0.3*z[,1]))
    W3 <- rbinom(n, size = 1, prob = plogis(-3+z[,1]))
    W4 <- rbinom(n, size = 1, prob = plogis(-1 + 0.1*z[,2]))
    W5 <- rbinom(n, size = 1, prob = plogis(2 + 0.5*z[,2]))
    W6 <- rbinom(n, size = 1, prob = plogis(-4 - 0.1*z[, 2]))
    W7 <- rbinom(n, size = 1, prob = plogis(2 - 0.2*z[,3]))
    W8 <- rbinom(n, size = 1, prob = plogis(-3 - 0.2*z[,3]))
    
    # Categorical variables
    W9 <- rbinom(n, size = 2, prob = plogis(-0.1 + 0.3*z[,1]))
    W10 <- rbinom(n, size = 4, prob = plogis(-0.8 + 0.2*log(5+z[, 2])))
    W11 <- rbinom(n, size=3, prob = plogis(-2+0.6*z[,2]))
    W12 <- rbinom(n, size = 3, prob = plogis(0.8+0.1*exp(z[,1])))
    # add support difference
    W9 <- ifelse(W9 == 2, 1, W9)
    W10 <- ifelse(W10 == 3, 0, W10)
    W10 <- ifelse(W10 == 4, 2, W10)

    # Ordinal variables
    z = z_all[, c(1, 2)]
    W13 = generate_y(z, omega = c(1, 0), K = 4, q=c(0.25, 0.5, 0.75))
    W14 = generate_y(z, omega = c(0, 1), K = 4, q=c(0.25, 0.5, 0.75))
    W15 = generate_y(z, omega = c(0.5, 0.8), K = 4, q=c(0.1, 0.2, 0.3))
    W16 = generate_y(z, omega = c(0.8, 0.5), K = 4, q=c(0.3, 0.4, 0.5))
    W17 = generate_y(z, omega = c(1, 1), K = 4, q=c(0.6, 0.7, 0.8))
    
    # Continuous variables
    zc = z_all[, c(1, 3)] 
    W18 = cos(zc[, 2]) + rnorm(n, mean = 0, sd = 1)
    W19 = zc[, 1] + zc[, 2] + rnorm(n, mean = 0, sd = 1)
    W20 = zc[, 1] * zc[, 2] + rnorm(n, mean = 0, sd = 1)
    
    return(tibble(W1, W2, W3, W4, W5, W6, W7, W8, W9, W10, W11, W12, W13, W14, W15, W16, W17, W18, W19, W20))
}
```



```{r 20 dim generate distribution f2}

generate_data2 <- function(n=50000, z_rho=0.8, mu=c(2, 3, 4), trt){ 
    sig = matrix(z_rho, 3, 3)
    diag(sig) = 1
    z_all = mvrnorm(n, mu=mu, Sigma=sig) 
    
    # Binary variables
    z = z_all
    W1 <- rbinom(n, size=1, prob=plogis(-1+0.3*z[, 1])) 
    W2 <- rbinom(n, size=1, prob=plogis(0.1*z[,1]))
    W3 <- rbinom(n, size = 1, prob = plogis(-0.3+6*z[,1]))
    W4 <- rbinom(n, size = 1, prob = plogis(-1 + 0.4*z[,2]))
    W5 <- rbinom(n, size = 1, prob = plogis(0.8 + 0.5*z[,2]))
    W6 <- rbinom(n, size = 1, prob = plogis(-4 + 0.1*z[, 2]))
    W7 <- rbinom(n, size = 1, prob = plogis(0.2 - 0.6*z[,3]))
    W8 <- rbinom(n, size = 1, prob = plogis(-2 + 0.2*z[,3]))
    
    # Categorical variables
    W9 <- rbinom(n, size = 2, prob = plogis(-0.5 + 0.6*z[, 1]))
    W10 <- rbinom(n, size = 4, prob = plogis(-0.4 + 0.2*exp(0.5*z[, 2])))
    W11 <- rbinom(n, size=3, prob = plogis(-2+0.1*z[,2]))
    W12 <- rbinom(n, size = 3, prob = plogis(0.5+0.8*exp(z[,1])))
    # add support difference
    W9 <- ifelse(W9 == 2, 1, W9)
    W10 <- ifelse(W10 == 3, 0, W10)
    W10 <- ifelse(W10 == 4, 2, W10)

    # add 5 ordinal variables with 2 latent dim
    z = z_all[, 1:2]
    W13 = generate_y(z, omega = c(0.9, 0), K = 4, q=c(0.1, 0.3, 0.5))
    W14 = generate_y(z, omega = c(0, 0.8), K = 4, q=c(0.1, 0.3, 0.5))
    W15 = generate_y(z, omega = c(0.1, 0.5), K = 4, q=c(0.2, 0.4, 0.6))
    W16 = generate_y(z, omega = c(0.2, 0.9), K = 4, q=c(0.2, 0.4, 0.6))
    W17 = generate_y(z, omega = c(1, -1), K = 4, q=c(0.2, 0.4, 0.6))
    
    # add 6 continuous variables with 2 latent dim
    zc = z_all[, c(1, 3)]
    
    W18 = sin(zc[, 2]) + rnorm(n, mean = 0, sd = 1)
    W18 = gen_range(W18, -2, 4, n)
    
    W19 = zc[, 1] - zc[, 2] + rnorm(n, mean = 0, sd = 1)+5
    W19 = gen_range(W19, -4, 13, n)
    
    W20 = zc[, 1] * 5 * zc[, 2] + rnorm(n, mean = 0, sd = 1)
    W20 = gen_range(W20, -5, 33, n)
    
    return(tibble(W1, W2, W3, W4, W5, W6, W7, W8, W9, W10, W11, W12, W13, W14, W15, W16, W17, W18, W19, W20))
}
```



```{r 20 dim generate distribution f3}

generate_data3 <- function(n=50000, z_rho=0.8, mu = c(3, 5, 7)){ 
    sig = matrix(z_rho, 3, 3)
    diag(sig) = 1
    z_all = mvrnorm(n, mu=mu, Sigma=sig) 
    
    # Binary variables
    z = z_all
    W1 <- rbinom(n, size=1, prob=plogis(-1+0.3*z[, 1])) 
    W2 <- rbinom(n, size=1, prob=plogis(0.1*z[,1]))
    W3 <- rbinom(n, size = 1, prob = plogis(-0.3+6*z[,1]))
    W4 <- rbinom(n, size = 1, prob = plogis(-1 + 0.4*z[,2]))
    W5 <- rbinom(n, size = 1, prob = plogis(0.8 + 0.5*z[,2]))
    W6 <- rbinom(n, size = 1, prob = plogis(-4 + 0.1*z[, 2]))
    W7 <- rbinom(n, size = 1, prob = plogis(0.2 - 0.6*z[,3]))
    W8 <- rbinom(n, size = 1, prob = plogis(-2 + 0.2*z[,3]))
    
    
    W9 <- rbinom(n, size = 2, prob = plogis(-0.5 + 0.6*z))
    W10 <- rbinom(n, size = 4, prob = plogis(-0.4 + 0.2*exp(0.5*z)))
    W11 <- rbinom(n, size =3, prob = plogis(-4+z[,2]^2))
    W12 <- rbinom(n, size = 3, prob = plogis(-1.5+0.8*exp(2*z[,1])))

    # add 5 ordinal variables with 2 latent dim
    z = z_all[, 1:2]
    W13 = generate_y(z, omega = c(0.9, 0), K = 4, q=c(0.1, 0.3, 0.5))
    W14 = generate_y(z, omega = c(0, 0.8), K = 4, q=c(0.1, 0.3, 0.5))
    W15 = generate_y(z, omega = c(0.1, 0.5), K = 4, q=c(0.2, 0.4, 0.6))
    W16 = generate_y(z, omega = c(0.2, 0.9), K = 4, q=c(0.8, 0.85, 0.9))
    W17 = generate_y(z, omega = c(1, -1), K = 4, q=c(0.8, 0.85, 0.9))
    
    # add 6 continuous variables with 2 latent dim
    zc = z_all[, c(1, 3)]
    
    W18 = sin(zc[, 2]) + rnorm(n, mean = 0, sd = 1)
    W19 = zc[, 1] - zc[, 2] + rnorm(n, mean = 0, sd = 1)
    W20 = zc[, 1] * 5 * zc[, 2] + rnorm(n, mean = 0, sd = 1)
    
    return(tibble(W1, W2, W3, W4, W5, W6, W7, W8, W9, W10, W11, W12, W13, W14, W15, W16, W17, W18, W19, W20))
}

```




## Simulation repeat 20 times
```{r}
set.seed(12345)
seeds = sample.int(1e8, 20)

for (i in seq_len(20)){
  set.seed(seeds[i])
  
  n_trt=2000
  n_big1 = 20000
  n_big2 = 80000
  n_big3 = 50000
  
  z_rho = runif(1, 0., 0.1)
  #z_rho = runif(1, 0.8, 0.85)
  print(z_rho)
  mu_trt = c(1, 2, 3) + rnorm(3, 0, 0.1)
  mu_big2 = c(2, 3, 4) + rnorm(3, 0, 0.1)
  mu_big3 = c(3, 5, 7) + rnorm(3, 0, 0.1)
  
  # trts
  trt = generate_data(n=n_trt, z_rho=z_rho, mu=mu_trt)
  print(sum(is.na(trt)))


  # big
  # real world big database with proportion 
  R1 = generate_data(n=n_big1, z_rho = z_rho, mu=mu_trt)
  R2 = generate_data2(n=n_big2, z_rho = z_rho, mu=mu_big2, trt = trt)
  R3 = generate_data3(n=n_big3, z_rho = z_rho, mu = mu_big3)
  big = rbind(R1, R2, R3)
  print(sum(is.na(big)))

  # create folder to save the simulations
  # n_trt, correlation, proportion, covariates dim
  dir_name = sprintf("+-++/rep%d", i)
  if (!dir.exists(dir_name)) dir.create(dir_name)
  
  saveRDS(trt, file = file.path(dir_name, "trt.rds"))
  saveRDS(big, file = file.path(dir_name, "big.rds"))
  
  saveRDS(list(seed=seeds[i]), file = file.path(dir_name, "metadata.rds"))
}
```

